// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package models

import (
	"database/sql"
	"time"
)

type User struct {
	ID           string
	AccessToken  string
	RefreshToken string
	CreatedAt    time.Time
	ExpiredAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}
